# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jesús Reyes Piernagorda (이해수)
title: Technical Support Engineer 
email: jesusrepi@gmail.com
website: https://www.linkedin.com/in/jesusreyesp/?locale=ko_KR

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  iYosuua
linkedin_username: jesusreyesp


# Google Analytics and Tag Manager
gtag: "G-RF2KKYBL7Z"


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jesús and I'm a <mark>motivate</mark> Software Support Engineer with over <mark>nine years</mark> of valuable experience in software support. 
  As well as Support Engineer I also have experience as Network Engineer and Sysadmin. Responsible and caring <mark>always willing to do what needs to get done</mark>, outgoing 
  profesional inspire to work with people and for people. Experience in deploy, designing and supporting enterpirse-level internet scale services/solutions hosted 
  on Cloud and On-premise technologies following SLA´s and Business KPI´s. I am an <mark>energetic</mark> and <mark>ambitious</mark> person who bringing forth a 
  motivated attitude and the ability to establish strong and productive relationships with other company members.
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Facephi Biometria S.A.
        link: https://facephi.com/
        # link_text: facephi.com
        sub_title: Technical Support Engineer N2
        caption: January 2022 - Present
        quote: >
          FacePhi provides secure, fast, and easy to use technology. Experts in user’s digital identity verification, it specialises in digital onboarding and biometric authentication solutions. 
        description: | # this will include new lines to allow paragraphs
            • APAC Area N2 technical support and dispatcher.
            • SaaS, API and SDK support in Digital onboarding and biometric authentication solutions.
            • Support platforms like Jira, Github, Confluence, CRM and Redmine management.
            • Integration support in frameworks (Ionic, Cordova, Capacitor, React Native, Flutter, …).
            • Android/iOS platforms deployment and Web (Angular, Vue, HTML and React).
            • ITIL Processes (KPI´s and SLA) and QA testing.
            • Maintaining documentation for all Helpdesk and end-user processes and procedures.
      - layout: left
        title: Lisec GmbH
        link: https://www.lisec.com/
        # link_text: lisec.com
        sub_title: Software Engineer
        caption: July 2018 - January 2022
        quote: >
          LiSEC has been producing glass processing machines, offering innovative single and system solutions in the field of flat glass processing and refining
        description: | # this will include new lines to allow paragraphs
            • Database administrator (Postgresql, Oracle, ...). 
            • ERP&CRM.
            • Ticket Support.
            • Event monitoring / incident handling.
            • Server built / configuration.
            • OS upgrades / patching (Windows Server, Linux, MAC OS X Server). 
            • Fulfillment of service requests.
      - layout: left
        title: Molisoft Grupo Empresarial S.L.
        link: https://molisoft.com/
        # link_text: molisoft.com
        sub_title: Noc Engineer
        caption: March 2013 - May 2018
        # quote: >
        #  FacePhi provides secure, fast, and easy to use technology. Experts in user’s digital identity verification, it specialises in digital onboarding and biometric authentication solutions. 
        description: | # this will include new lines to allow paragraphs
            • Installation and maintenance of all DOCSIS systems.
            • Network monitoring.
            • Building, configuration and troubleshooting of server and desktop hardware.
            • Providing advice on selection and purchase of IT equipment.
            • Maintaining maximum availability of supported services for users.
            • Designing, implementing and managing Linux services.
            • Monitoring the progress of third-party maintenance contract suppliers. Ensuring that support calls are logged and handled effectively and efficiently.
            • Responsible for disaster recovery, closing security loopholes and access levels.
            • Identify and recommending improvements for IT Products.
 # - title: Projects # Title for the section
 #   layout: list # Type of content section (list/text)
 #   content:
 #     - layout: top-middle
 #       title: Super awesome project
 #       link: github.com/sproogen
        # link_text: Project Website
 #       additional_links:
 #         - title:  sproogen/modern-resume-theme
 #           icon: fab fa-github
 #           url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
 #         quote: >
 #          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
 #        description: | # this will include new lines to allow paragraphs
 #          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
