# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jesús Reyes Piernagorda (이해수)
title: Technical Support Engineer 
email: jesusrepi@gmail.com
website: https://www.linkedin.com/in/jesusreyesp/

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  iYosuua
linkedin_username: jesusreyesp


# Google Analytics and Tag Manager
gtag: "G-RF2KKYBL7Z"


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a <mark>Technical Support Engineer with 12 years of experience</mark>, specializing in networking, data storage solutions, system deployments, and both Linux and Windows environments.
  I'm passionate about emerging technologies and always looking to expand my technical skills.
  Throughout my career, I've developed a knack for <mark>quickly resolving complex issues</mark> in fast-paced environments. My experience in B2B technical organizations has shaped my leadership style, whether Im mentoring colleagues or tackling challenges head-on.
  <mark>Fluent in both Spanish and English</mark>, I’m able to effectively bridge communication gaps between teams and clients. I’m also committed to creating clear and comprehensive <mark>KCS documentation</mark> to improve self-service options and streamline case resolution.
  With a <mark>strong technical background, a solid work ethic, and a collaborative approach</mark>, I aim to drive success in every role I take on in software support and solutions engineering.
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NetApp, Inc.
        link: https://www.netapp.com/
        # link_text: netapp.com
        sub_title: Technical Support Engineer Level 2 Oncommand
        caption: February 2023 - Now
        quote: >
          NetApp, Inc. is an American data infrastructure company that provides unified data storage, integrated data services, and cloud operations solutions to enterprise customers.
        description: | # this will include new lines to allow paragraphs
            * Provided technical support for monitoring NetApp storage systems, including Active IQ Unified Manager, Data Infrastructure Insights, ONTAP System Manager, and Active IQ Digital Advisor. 
            * Troubleshot REST APIs, storage health and performance issues, and OS environment problems across both on-premises and cloud infrastructures, ensuring quick issue resolution.
            * Configured and managed alerts and notifications for system issues and failures, enhancing proactive monitoring and incident response.
            * Created and maintained technical documentation and knowledge base articles as a Knowledge-Centered Service (KCS) Publisher, improving self-service support and reducing case resolution time.
            * Delivered exceptional customer support, achieving a 95% customer satisfaction rating through effective troubleshooting, clear communication, and timely resolution of complex issues.
      - layout: left
        title: Facephi Biometria S.A.
        link: https://facephi.com/
        # link_text: facephi.com
        sub_title: Technical Support Engineer Level 2
        caption: January 2022 - January 2023
        quote: >
          FacePhi provides secure, fast, and easy to use technology. Experts in user’s digital identity verification, it specialises in digital onboarding and biometric authentication solutions. 
        description: | # this will include new lines to allow paragraphs
            * Provided Level 2 technical support and served as a dispatcher for the APAC region, ensuring timely issue resolution and seamless communication between teams.
            * Delivered SaaS, API, and SDK support for digital onboarding and biometric authentication solutions, assisting clients with integration and troubleshooting.
            * Supported and managed technical platforms including Jira, GitHub, Confluence, CRM, and Redmine to streamline issue tracking and documentation.
            * Assisted in integration support for mobile and web frameworks such as Ionic, Cordova, Capacitor, React Native, and Flutter, ensuring smooth deployment.
            * Provided Android/iOS deployment support and web development assistance for technologies like Angular, Vue, HTML, and React.
            * Adhered to ITIL processes, monitored KPIs and SLAs, and participated in QA testing to enhance service quality and efficiency.
            * Managed software licensing for biometric authentication solutions, ensuring compliance, renewal tracking, and proper allocation across clients and internal teams.
      - layout: left
        title: Lisec GmbH
        link: https://www.lisec.com/
        # link_text: lisec.com
        sub_title: Technical Support Specialist
        caption: July 2018 - January 2022
        quote: >
          Molisoft is an ISP specializing in reliable networking solutions and expert technical support, ensuring seamless and secure internet connectivity for businesses and individuals.
        description: | # this will include new lines to allow paragraphs
            * Provided technical support, resolving complex issues related to order management, production planning, data analysis, and machine integration in the flat glass industry. 
            * Acted as a Database Administrator (PostgreSQL, Oracle, etc.), ensuring database optimization, backup management, and troubleshooting performance issues.
            * Supported ERP & CRM systems, assisting with configuration, data integrity, and workflow automation to enhance operational efficiency.
            * Handled server builds and configurations, ensuring optimal setup for Windows Server, Linux, and macOS X Server environments.
            * Executed OS upgrades, patching, and security updates, maintaining system stability and compliance with industry standards.
      - layout: left
        title: Molisoft Grupo Empresarial S.L.
        link: https://molisoft.com/
        # link_text: molisoft.com
        sub_title: Noc Engineer
        caption: March 2013 - May 2018
        quote: >
          FacePhi provides secure, fast, and easy to use technology. Experts in user’s digital identity verification, it specialises in digital onboarding and biometric authentication solutions. 
        description: | # this will include new lines to allow paragraphs
            • Installed, maintained, and optimized DOCSIS systems, ensuring reliable broadband services for local TV, internet, and telephony providers.
            • Monitored network performance to detect, analyze, and resolve faults, minimizing service disruptions and ensuring maximum uptime.
            • Built, configured, and troubleshot server and desktop hardware, ensuring optimal system performance and longevity.
            • Provided expert guidance on IT equipment selection and procurement, balancing performance, scalability, and cost-efficiency.
            • Ensured high availability of critical services, proactively addressing system failures, congestion issues, and security risks.
            • Designed, implemented, and managed Linux-based services, supporting infrastructure for telecom and ISP operations.
            • Supervised and coordinated third-party maintenance contracts, ensuring service calls were logged, tracked, and resolved efficiently.
            • Implemented disaster recovery strategies, security hardening, and access control policies to mitigate risks and protect sensitive data.
            • Evaluated and recommended IT product and service improvements, enhancing operational efficiency and service quality.
 # - title: Projects # Title for the section
 #   layout: list # Type of content section (list/text)
 #   content:
 #     - layout: top-middle
 #       title: Super awesome project
 #       link: github.com/sproogen
        # link_text: Project Website
 #       additional_links:
 #         - title:  sproogen/modern-resume-theme
 #           icon: fab fa-github
 #           url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
 #         quote: >
 #          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
 #        description: | # this will include new lines to allow paragraphs
 #          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
 # - title: Education # Title for the section
 #   layout: list # Type of content section (list/text)
 #   content:
 #     - layout: left
 #       title: Harvard University
 #       caption: 2010 - 2013
 #       sub_title: BSc Computer Science
 #       quote: >
 #         Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
 #       description: | # this will include new lines to allow paragraphs
 #         During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
 #         I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
 # - title: A Little More About Me
 #   layout: text
 #   content: | # this will include new lines to allow paragraphs
 #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
 #     - Rock climbing
 #     - Gaming
 #     - Knitting
 #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
 #     Look at this cool image  
 #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
